### ISSUE TITLE
Add farmOS Link

### ISSUE THREAD

**Issue by braughtg** [dickinson-comp190/GitKit-FarmData2-F22#30]
Change the word "farmOS" into a link in the Acknowledgements at the bottom of README.md.  

The URL to use for the link is: https://farmos.org/

The "Links" section of the following document shows how to create a link using Markdown:
- https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by quannn22** [comment]
I would like to work on this please!

**Comment by nathang15** [comment]
I would like to work on this please!

**Comment by fredam2025** [comment]
I would like to work on this please!

**Comment by Shahir-47** [comment]
I would like to work on this please!

**Comment by richmango03** [comment]
I would like to work on this please!

**Comment by saiatl2354** [comment]
I would like to work on this please!

**Comment by saiatl2354** [comment]
I would like to work on this please!

**Comment by maliham31** [comment]
I would like to work on this please!

**Comment by maliham31** [comment]
I would like to work on this please!
